// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA-gGMlGarXulbtsvHYsFcfGroAMcdFF0',
    appId: '1:923626442750:web:e0897206de5969fedabaaf',
    messagingSenderId: '923626442750',
    projectId: 'bank-sampah-app-ed9cb',
    authDomain: 'bank-sampah-app-ed9cb.firebaseapp.com',
    storageBucket: 'bank-sampah-app-ed9cb.firebasestorage.app',
    measurementId: 'G-JNG56Y4JKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBGPtevPZLO0xaN9LvimPHbdXwMTbFQmE',
    appId: '1:923626442750:android:2973af937193e051dabaaf',
    messagingSenderId: '923626442750',
    projectId: 'bank-sampah-app-ed9cb',
    storageBucket: 'bank-sampah-app-ed9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8buWJLJjBYmHU5794WvAV07ZvWJTmaGo',
    appId: '1:923626442750:ios:0940dfbdd9400bacdabaaf',
    messagingSenderId: '923626442750',
    projectId: 'bank-sampah-app-ed9cb',
    storageBucket: 'bank-sampah-app-ed9cb.firebasestorage.app',
    iosBundleId: 'app.gogeniusdev.simaru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8buWJLJjBYmHU5794WvAV07ZvWJTmaGo',
    appId: '1:923626442750:ios:beb0510e6531ba3edabaaf',
    messagingSenderId: '923626442750',
    projectId: 'bank-sampah-app-ed9cb',
    storageBucket: 'bank-sampah-app-ed9cb.firebasestorage.app',
    iosBundleId: 'com.example.bankSampahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA-gGMlGarXulbtsvHYsFcfGroAMcdFF0',
    appId: '1:923626442750:web:18156a67976e5610dabaaf',
    messagingSenderId: '923626442750',
    projectId: 'bank-sampah-app-ed9cb',
    authDomain: 'bank-sampah-app-ed9cb.firebaseapp.com',
    storageBucket: 'bank-sampah-app-ed9cb.firebasestorage.app',
    measurementId: 'G-NXFJQY1SW3',
  );

}